builds:
- env:
  - CGO_ENABLED=0
  goos: 
    - linux
    - darwin
    - windows
  ldflags:
     - -s -w -X finala/cmd.version={{.Version}} -X finala/cmd.commit={{.Commit}} -X finala/cmd.date={{.Date}} -X finala/cmd.builtBy=goreleaser
archives:
  - id: finala
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next" 
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  prerelease: auto