language: go
os:
- linux
# use the latest ubuntu environment (18.04) available on travis
dist: bionic

# Force-enable Go modules. Also force go to use the code in vendor/
# These will both be unnecessary when Go 1.14 lands.
env: GO111MODULE=on GOFLAGS='-mod vendor'

go:
  - 1.13.x

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
#install: true

notifications:
  email: false

before_script:
  - echo "kaplan kaplan"
# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - make test
