name: Go
on: [push]
jobs:

  spectralops:
    name: spectralops
    runs-on: ubuntu-latest
    steps:
    - name: Spectral Scan
      run: |
        curl -L spectralops.io/get | sudo sh
        spectral github similarweb/finala --dest similarweb/finala --kind repo

  test:
    name: Code Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1   
    - name: Run tests
      run: |
        make test 

